[amebr]
block-height = 222
block-width = 142
color = "375"
cover-height = 233
cover-width = 139
title = "American Bene. Review (The)"

[amisbl]
block-height = 205
block-width = 272
color = "488"
cover-height = 282
cover-width = 199
title = "Ami de St-Benoit-du-lac (L')"

[bib]
block-height = 233
block-width = 147
color = "488"
cover-height = 244
cover-width = 144
title = "Biblica"

[bulaim]
block-height = 205
block-width = 140
color = "035"
cover-height = 218
cover-width = 134
title = "Bulletin de L'A.I.M."

[bulhb]
block-height = 242
block-width = 151
color = "070"
cover-height = 252
cover-width = 147
title = "Bulletin d'Histroire Benedictine"

[bulle]
block-height = 231
block-width = 150
color = "488"
cover-height = 243
cover-width = 148
title = "Bulletin de Litt. Eccl."

[cahe]
block-height = 186
block-width = 172
color = "070"
cover-height = 196
cover-width = 167
title = "Cahiers Evangile"

[car]
block-height = 207
block-width = 150
color = "375"
cover-height = 220
cover-width = 146
title = "Carmel"

[catbq]
block-height = 222
block-width = 144
color = "423"
cover-height = 235
cover-width = 140
title = "Cath. Biblical Quarterly (The)"

[cel]
block-height = 240
block-width = 185
color = "488"
cover-height = 250
cover-width = 181
title = "Celebrer"

[chr]
block-height = 215
block-width = 147
color = "035"
cover-height = 227
cover-width = 143
title = "Christus"

[cissq]
block-height = 222
block-width = 144
color = "610"
cover-height = 234
cover-width = 141
title = "Cister. Studies Quar. (The)"

[colc]
block-height = 224
block-width = 146
color = "375"
cover-height = 237
cover-width = 146
title = "Collectanea Cisterciensia"

[coma]
block-height = 220
block-width = 134
color = "460"
cover-height = 230
cover-width = 130
title = "Communio Anglais"

[comf]
block-height = 206
block-width = 143
color = "370"
cover-height = 221
cover-width = 138
title = "Communio Francais"

[con]
block-height = 203
block-width = 128
color = "035"
cover-height = 215
cover-width = 125
title = "Contacts"

[conpe]
block-height = 233
block-width = 148
color = "090"
cover-height = 243
cover-width = 144
title = "Conn. des Peres de l'Eglise"

[conti]
block-height = 274
block-width = 209
color = "460"
cover-height = 284
cover-width = 203
title = "Continuite"

[docc]
block-height = 252
block-width = 175
color = "650"
cover-height = 263
cover-width = 170
title = "Documentation Catholique"

[dowr]
block-height = 205
block-width = 131
color = "442"
cover-height = 215
cover-width = 129
title = "Downside Review"

[ecco]
block-height = 235
block-width = 154
color = "037"
cover-height = 247
cover-width = 152
title = "Ecclesia Orans"

[ens]
block-height = 274
block-width = 204
color = "375"
cover-height = 286
cover-width = 198
title = "Ensemble"

[ephl]
block-height = 228
block-width = 160
color = "070"
cover-height = 243
cover-width = 156
title = "Ephemerides Liturgicae"

[ephtl]
block-height = 237
block-width = 153
color = "375"
cover-height = 250
cover-width = 147
title = "Ephemerides Theo. Lovanienses"

[esn]
block-height = 210
block-width = 133
color = "750"
cover-height = 220
cover-width = 127
title = "En Son Nom"

[espv]
block-height = 268
block-width = 177
color = "750"
cover-height = 278
cover-width = 175
title = "Esprit et Vie"

[etuhr]
block-height = 220
block-width = 142
color = "035"
cover-height = 230
cover-width = 138
title = "Etudes d'Histoire Religieuse"

[etu]
block-height = 229
block-width = 148
color = "320"
cover-height = 241
cover-width = 144
title = "Etudes"

[feun]
block-height = 224
block-width = 151
color = "037"
cover-height = 237
cover-width = 149
title = "Feu Nouveau"

[geof]
block-height = 266
block-width = 206
color = "090"
cover-height = 275
cover-width = 200
title = "Geo France"

[ges]
block-height = 204
block-width = 142
color = "090"
cover-height = 217
cover-width = 137
title = "Gesta"

[gre]
block-height = 223
block-width = 151
color = "375"
cover-height = 233
cover-width = 150
title = "Gregorianum"

