# booklet-test-2.toml


[ticket.t1]
pub-key = "maid"
volumes = [["2023", 56]]

[ticket.t2]
pub-key = "amebr"
volumes = [["2023", 40]]

[ticket.t3]
pub-key = "chr"
volumes = [["2023", 29]]

[ticket.t4]
pub-key = "nourt"
volumes = [["2023", 36]]

[ticket.t5]
pub-key = "etu"
volumes = [["2022-1", 45], ["2022-2", 39], ["2023-1", 45], ["2023-2", 40]]

[ticket.t6]
pub-key = "viec"
volumes = [["2023", 29]]

[ticket.t7]
pub-key = "catbq"
volumes = [["2023", 51]]

[ticket.t8]
pub-key = "revhe"
volumes = [["2021-1", 36], ["2021-2", 38]]

[ticket.t9]
pub-key = "catbq"
volumes = [["2022", 47]]

[ticket.t10]
pub-key = "natgf"
volumes = [["2022-1", 39], ["2022-2", 44], ["2023-1", 42], ["2023-2", 44]]

[ticket.t11]
pub-key = "monb"
volumes = [["2023", 37]]

[ticket.t12]
pub-key = "comf"
volumes = [["2023", 45]]

[ticket.t13]
pub-key = "con"
volumes = [["2023", 29]]

[ticket.t14]
pub-key = "ecco"
volumes = [["2021", 50]]

[ticket.t15]
pub-key = "colc"
volumes = [["2022", 36], ["2023", 31]]

[ticket.t16]
pub-key = "lit"
volumes = [["2022", 32]]

[ticket.t17]
pub-key = "novv"
volumes = [["2022", 41], ["2023", 41]]

[ticket.t18]
pub-key = "bulle"
volumes = [["2022", 44], ["2023", 43]]

[ticket.t19]
pub-key = "pri"
volumes = [["2023", 33]]

[ticket.t20]
pub-key = "revt"
volumes = [["2022", 72]]

[ticket.t21]
pub-key = "revspt"
volumes = [["2022", 44]]

[ticket.t22]
pub-key = "feun"
volumes = [["2022-2023 A", 50]]

[ticket.t23]
pub-key = "cissq"
volumes = [["2022", 39]]

[ticket.t24]
pub-key = "ist"
volumes = [["2022", 45], ["2023", 42]]

[ticket.t25]
pub-key = "bib"
volumes = [["2022", 53]]

[ticket.t26]
pub-key = "ques"
volumes = [["2023", 30]]

[ticket.t27]
pub-key = "pasq"
volumes = [["2022-2023", 31]]

[ticket.t28]
pub-key = "geof"
volumes = [["2023-1", 40], ["2023-2", 44]]

[ticket.t29]
pub-key = "revsr"
volumes = [["2022", 34], ["2023", 32]]

[ticket.t30]
pub-key = "revbib"
volumes = [["2022", 52], ["2023", 52]]

[ticket.t31]
pub-key = "revtl"
volumes = [["2022", 49]]

[ticket.t32]
pub-key = "revhe"
volumes = [["2022", 37], ["2023", 39]]

[ticket.t33]
pub-key = "revben"
volumes = [["2023", 39]]

[ticket.t34]
pub-key = "bulhb"
volumes = [["2023", 17]]

[ticket.t35]
pub-key = "sciv"
volumes = [["2023", 31]]


[booklet]
pages = [["t1", "t2", "t3", "t4", "t5", "t6"],
         ["t7", "t8", "t9", "t10", "t11"],
	 ["t12", "t13", "t14", "t15", "t16"],	 
	 ["t17", "t18", "t19", "t20", "t21"],
	 ["t22", "t23", "t24", "t25", "t26"],
	 ["t27", "t28", "t29", "t30", "t31"],
	 ["t32", "t33", "t34", "t35"]]

