# booklets-example.toml
#
# Define your tickets. Ticket keys (names) must be unique.
# Then arrange your tickets into pages in a booklet.
# A booklet is defined by an array of arrays. 
# Each row in the pages array is one page of tickets.
#
# You can have as many booklets as you like, 
# just give them unique names.
# 
# A ticket key looks like this
#
# ticket.XXXXX
# 
# The first part has to be "ticket" but you can put any unique
# name after the dot. The reference to your ticket in the booklet
# has to match this unique ticket identifier.


[ticket.t1]
pub-key = "letal"
volumes = [["2019-2021", 25]]

[ticket.t2]
pub-key = "catbq"
volumes = [["2020", 48], ["2021", 47]]

[ticket.t3]
pub-key = "car"
volumes = [["2021", 29], ["2022", 28]]

[ticket.t4]
pub-key = "etu"
volumes = [["2020-1", 40], ["2020-2", 40], ["2021-1", 34], ["2021-2", 41]]

[ticket.t5]
pub-key = "revhe"
volumes = [["2021-1", 36], ["2021-2", 38]]

[ticket.t6]
pub-key = "geof"
volumes = [["2021-1", 41], ["2021-2", 43], ["2022-1", 41], ["2022-2", 41]]

[ticket.t7]
pub-key = "sourd"
volumes = [["2004-2011", 48], ["2012-2022", 36]]

[ticket.t8]
pub-key = "esn"
volumes = [["2013-2015", 43], ["2021-2022", 34]]

[ticket.t9]
pub-key = "ist"
volumes = [["2012", 33], ["2021", 40]]

[ticket.t10]
pub-key = "con"
volumes = [["2021", 33], ["2022", 28]]

[ticket.t11]
pub-key = "etuhr"
volumes = [["2022-1", 45], ["2022-2", 39], ["2023-1", 45], ["2023-2", 40]]

[ticket.t12]
pub-key = "natgf"
volumes = [["2022-1", 39], ["2022-2", 44], ["2023-1", 42], ["2023-2", 44]]

[booklet]
filename = 'booklet-example'
pages = [["t1", "t2", "t3"],
         ["t4", "t5", "t6"],
	 ["t7", "t8", "t9", "t10"],
	 ["t11", "t12"]
	 ]








